name: Build And Push Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: イメージパス
        required: true
        type: string
      dockerfile:
        description: Dockerfileのパス
        required: true
        type: string
        default: deployment/Dockerfile
      registry:
        description: イメージプッシュ先レジストリ
        required: false
        type: string
        default: ghcr.io
      registry_user:
        description: レジストリユーザー名
        required: false
        type: string
        default: ${{ github.actor }}
    secrets:
      registry_pass:
        description: レジストリパスワード
        required: true
        # default: ${{ secrets.GITHUB_TOKEN }} # secretsはdefault指定できない

jobs:
  build:
    name: Build And Push Docker Image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout target repository
        id: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Buildx
        id: builder
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.1

      - name: Login to Github Container Registry
        id: login
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry_user }}
          password: ${{ secrets.registry_pass }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ inputs.registry }}/${{ inputs.image }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch,suffix=-{{sha}}
            type=ref,event=pr,prefix=pr-,suffix=-{{sha}}

      - name: Build and Push Image
        id: build-push
        uses: docker/build-push-action@v2
        with:
          file: ${{ inputs.dockerfile }}
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
