name: Build And Push Docker Image[ghcr.io]

on:
  workflow_call:
    inputs:
      image:
        description: image name
        required: true
        type: string
      dockerfile:
        description: path to Dockerfile
        required: false
        type: string
        default: Dockerfile

jobs:
  build:
    name: Build And Push Docker Image
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: setup
        uses: mintak21/actions/.github/actions/setup_build
        with:
          image: ghcr.io/${{ inputs.image }}

      - name: Login to Github Container Registry
        id: login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        id: build-push
        uses: docker/build-push-action@v2
        with:
          file: ${{ inputs.dockerfile }}
          context: .
          push: true
          tags: ${{ steps.setup.outputs.tags }}
          labels: ${{ steps.setup.outputs.labels }}
