name: Github Actions Version Updater

on:
  schedule:
    - cron: "0 6 * * 5"
  push:
    branches:
      - main # TODO
  workflow_dispatch:

jobs:
  terraform-updater:
    name: actions version updater(related terraform)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repositry:
          - mintak21/terraform
        package:
          - terraform
          # - tflint
          # - tfsec
        include:
          - package: terraform
            repository: "hashicorp/terraform"
          - package: tflint
            repository: "terraform-linters/tflint"
          - package: tfsec
            repository: "aquasecurity/tfsec"
      fail-fast: false
    env:
      COMITTER: version-update-bot

    steps:
      - name: Get Latest Version
        id: latest-versions
        run: |
          latest=$(curl -H "Content-Type: application/json" https://api.github.com/repos/${{ matrix.repository }}/releases | jq -r '.[] | select(.prerelease|not) | .name' | sort -rn | head -n 1 | sed "s/v//g")
          echo "version=${latest}" >> $GITHUB_ENV
          echo ${{ matrix.package }} ${latest}

      - name: Checkout target repository
        id: checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.target_repositry }}
          token: ${{ secrets.TOKEN_GITHUB }}

      - name: Create commits
        id: commit
        run: |
          git config user.name '${{ env.COMITTER }}'
          git config user.email '${{ env.COMITTER }}@users.noreply.github.com'

          sed -i -e "s/${{ matrix.package }}=.*/${{ matrix.package }}=${{ env.latest }}/" .github/workflows/versions
          # git commit -am ":robot: automatic update ${{ matrix.package }} to ${{ env.latest }}"

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          commit-message: ":robot: automatic update ${{ matrix.package }} to ${{ env.latest }}"
          committer: ${{ env.COMITTER }} <${{ env.COMITTER }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: "[Example] Update report"
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/mintak21/actions-version-updater/actions/runs/${{ github.run_id }}
          labels: |
            automated pr
            ${{ matrix.package }}
          assignees: peter-evans
          reviewers: mintak21
          draft: false
